version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: voters-db
    environment:
      POSTGRES_DB: voters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d voters"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
