# This file is generated by post.sh after a terraform apply.
# It contains the connection details for the database.
# Do not commit this file to version control.

export PGHOST="terraform-20250612154245863900000001.c3xsdafekpkg.eu-west-1.rds.amazonaws.com"
export PGPORT="5432"
export PGDATABASE="voters"
export PGUSER="voteradmin"
export PGPASSWORD="PUXATr0whIuHfA#H"

echo "Database environment variables set."
