#!/usr/bin/env bash

# This script is executed by do-terraform.sh after a successful 'apply'.
# It fetches the database connection details from Terraform outputs and
# creates a db-env.sh file in the project root to be sourced by other scripts.

set -euo pipefail

echo "--- Post-Apply: Fetching DB connection details ---"

ENV_FILE="db-env.sh" # Creates the file in the current dir (infra/db)

# Ensure terraform is initialized so we can read outputs
terraform init > /dev/null

# Fetch outputs
DB_ENDPOINT=$(terraform output -raw db_instance_endpoint)
DB_NAME=$(terraform output -raw db_name)
DB_USER=$(terraform output -raw db_username)
DB_PASSWORD=$(terraform output -raw db_password)
DB_HOST="${DB_ENDPOINT%:*}"
DB_PORT="${DB_ENDPOINT##*:}"

# Create the db-env.sh file
cat > "${ENV_FILE}" << EOL
# This file is generated by post.sh after a terraform apply.
# It contains the connection details for the database.
# Do not commit this file to version control.

export PGHOST="${DB_HOST}"
export PGPORT="${DB_PORT}"
export PGDATABASE="${DB_NAME}"
export PGUSER="${DB_USER}"
export PGPASSWORD="${DB_PASSWORD}"

echo "Database environment variables set."
EOL

echo "Successfully created ${PWD}/${ENV_FILE}"
echo "You can now source this file to configure your shell for psql:"
echo "source ${PWD}/${ENV_FILE}"
echo "--- Post-Apply: Complete ---" 