CREATE TABLE addresses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address TEXT NOT NULL, -- For street lines, P.O. Box, etc.
    place_id BIGINT NOT NULL,
    postcode VARCHAR(10) NOT NULL,
    FOREIGN KEY (place_id) REFERENCES places(id),
    FOREIGN KEY (postcode) REFERENCES con_postcodes(postcode)
);

COMMENT ON TABLE addresses IS 'Stores address components for voters and potentially other entities.';
COMMENT ON COLUMN addresses.id IS 'Unique identifier for the address.';
COMMENT ON COLUMN addresses.address IS 'Full street address lines, excluding place/city and postcode.';
COMMENT ON COLUMN addresses.place_id IS 'Reference to the city/town/village from the places table.';
COMMENT ON COLUMN addresses.postcode IS 'The postcode for this address, linked to a constituency postcode.';

ALTER TABLE addresses ADD CONSTRAINT uq_address_full UNIQUE (address, place_id, postcode); 