CREATE TABLE citizens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status CHAR(1) DEFAULT 'B',
    died DATE DEFAULT NULL,
    FOREIGN KEY (status) REFERENCES citizen_statuses(status_code)
);




