CREATE TABLE citizens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    surname VARCHAR(255) NOT NULL,
    first_names VARCHAR(255) NOT NULL,
    gender CHAR(1),
    status CHAR(1) DEFAULT 'B',
    died DATE DEFAULT NULL,
    notes TEXT,
    FOREIGN KEY (status) REFERENCES citizen_statuses(status_code)
);




