CREATE TABLE voters (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    citizen_id BIGINT UNIQUE NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postcode VARCHAR(10) NOT NULL,
    voter_status CHAR(1) NOT NULL,
    open_register BOOLEAN DEFAULT FALSE,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (citizen_id) REFERENCES citizens(id),
    FOREIGN KEY (voter_status) REFERENCES voter_status(code),
    FOREIGN KEY (postcode) REFERENCES con_postcodes(postcode)
); 