CREATE TABLE IF NOT EXISTS voters (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    citizen_id BIGINT UNIQUE NOT NULL,
    address_id BIGINT NOT NULL,
    voter_status CHAR(1) NOT NULL,
    open_register BOOLEAN DEFAULT FALSE,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (citizen_id) REFERENCES citizens(id),
    FOREIGN KEY (voter_status) REFERENCES voter_status(code),
    FOREIGN KEY (address_id) REFERENCES addresses(id)
); 

COMMENT ON TABLE voters IS 'Registered voters.';
COMMENT ON COLUMN voters.address_id IS 'Reference to the voter\'s address in the addresses table.'; 