CREATE TABLE IF NOT EXISTS voters (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    citizen_id INTEGER UNIQUE NOT NULL,
    address_id BIGINT NOT NULL,
    open_register BOOLEAN DEFAULT FALSE,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (citizen_id) REFERENCES citizen(id),
    FOREIGN KEY (address_id) REFERENCES addresses(id)
); 

COMMENT ON TABLE voters IS 'Registered voters.';
COMMENT ON COLUMN voters.citizen_id IS 'Reference to the citizen record.';
COMMENT ON COLUMN voters.address_id IS 'Reference to the voter\'s address in the addresses table.';
COMMENT ON COLUMN voters.open_register IS 'Whether the voter is on the open register (publicly visible).';
COMMENT ON COLUMN voters.registration_date IS 'Date when the voter registered to vote.'; 